version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/clean-ts-api
    restart: always
    command: bash -c "npm install --omit=dev && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-ts-api
    volumes:
      - ./dist/:/usr/src/clean-ts-api/dist/
      - ./package.json:/usr/src/clean-ts-api/package.json
    ports:
      - "3030:3030"
      - "9222:9222"
    links:
      - mongo